'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { useTelemetry } from './TelemetryProvider'

// ── Ambient light presets ────────────────────────────────────────

const AMBIENT_PRESETS = {
  off:        { mode: 0, r: 0,    g: 0,    b: 0,    lum: 0    },
  matte:      { mode: 1, r: 0.35, g: 0.15, b: 0.08, lum: 0.22 },
  reflective: { mode: 2, r: 0.45, g: 0.18, b: 0.10, lum: 0.30 },
} as const

type AmbientMode = keyof typeof AMBIENT_PRESETS

// Color cycling speed (radians per second)
const COLOR_CYCLE_SPEED = 0.15

/**
 * Embeds the real dashboard HUD in an iframe, feeding it telemetry
 * data via postMessage. The dashboard-embed.html is generated by
 * `scripts/build-web-demo.mjs` from the actual dashboard source.
 */
export function DashboardEmbed() {
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const { data, status } = useTelemetry()
  const [ambientMode, setAmbientMode] = useState<AmbientMode>('off')
  const ambientRef = useRef<AmbientMode>('off')
  const animRef = useRef<number>(0)

  // Keep ref in sync for RAF loop
  ambientRef.current = ambientMode

  // ── Post telemetry data to iframe on every update ──
  useEffect(() => {
    const iframe = iframeRef.current
    if (!iframe?.contentWindow || !data) return
    iframe.contentWindow.postMessage(
      { type: 'k10-telemetry', snapshot: data },
      '*',
    )
  }, [data])

  // ── Ambient light color cycling loop ──
  const tickAmbient = useCallback(() => {
    const iframe = iframeRef.current
    if (iframe?.contentWindow) {
      const preset = AMBIENT_PRESETS[ambientRef.current]
      if (preset.mode > 0) {
        // Slowly cycle hue for a living-room demo feel
        const t = Date.now() / 1000
        const hueShift = Math.sin(t * COLOR_CYCLE_SPEED) * 0.5 + 0.5
        const r = preset.r + Math.sin(t * COLOR_CYCLE_SPEED) * 0.12
        const g = preset.g + Math.sin(t * COLOR_CYCLE_SPEED + 2.1) * 0.08
        const b = preset.b + Math.sin(t * COLOR_CYCLE_SPEED + 4.2) * 0.06
        iframe.contentWindow.postMessage({
          type: 'k10-ambient',
          mode: preset.mode,
          r: Math.max(0, Math.min(1, r)),
          g: Math.max(0, Math.min(1, g)),
          b: Math.max(0, Math.min(1, b)),
          lum: preset.lum + hueShift * 0.05,
        }, '*')
      } else {
        iframe.contentWindow.postMessage({
          type: 'k10-ambient',
          mode: 0, r: 0, g: 0, b: 0, lum: 0,
        }, '*')
      }
    }
    animRef.current = requestAnimationFrame(tickAmbient)
  }, [])

  useEffect(() => {
    animRef.current = requestAnimationFrame(tickAmbient)
    return () => cancelAnimationFrame(animRef.current)
  }, [tickAmbient])

  return (
    <div className="flex flex-col gap-3">
      {/* Ambient mode selector */}
      <div className="flex items-center justify-between">
        <span className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)]">
          Live Dashboard Demo
        </span>
        <div className="flex items-center gap-2">
          <span className="text-[9px] uppercase tracking-wider text-[var(--text-muted)]">
            Ambient
          </span>
          <select
            value={ambientMode}
            onChange={(e) => setAmbientMode(e.target.value as AmbientMode)}
            className="text-[10px] bg-[var(--bg-surface)] border border-[var(--border-subtle)] rounded px-2 py-1 text-[var(--text-secondary)] font-mono cursor-pointer"
          >
            <option value="off">Off</option>
            <option value="matte">Matte</option>
            <option value="reflective">Reflective</option>
          </select>
        </div>
      </div>

      {/* Dashboard iframe */}
      <div
        className="relative rounded-xl overflow-hidden border border-[var(--border-subtle)]"
        style={{ aspectRatio: '16 / 7' }}
      >
        {status !== 'live' && (
          <div className="absolute inset-0 flex items-center justify-center bg-[var(--bg-surface)] z-10">
            <span className="text-sm text-[var(--text-dim)] animate-pulse">
              Connecting to telemetry...
            </span>
          </div>
        )}
        <iframe
          ref={iframeRef}
          src="/_demo/dashboard-embed.html"
          title="K10 Motorsports Dashboard Demo"
          className="w-full h-full border-0"
          sandbox="allow-scripts"
          style={{
            background: '#0a0a14',
            opacity: status === 'live' ? 1 : 0,
            transition: 'opacity 0.5s ease',
          }}
        />
      </div>
    </div>
  )
}
