'use client'

import { useEffect, useRef, useState } from 'react'
import { useTelemetry } from './TelemetryProvider'

// The dashboard content is ~1200px wide at native size. We render the
// iframe at this width and scale it to fit whatever container we're in.
const NATIVE_W = 1200
const NATIVE_H = 260

/**
 * Embeds the real dashboard HUD in an iframe, feeding it telemetry
 * data via postMessage. The dashboard-embed.html is generated by
 * `scripts/build-web-demo.mjs` from the actual dashboard source.
 */
export function DashboardEmbed() {
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)
  const { data, status } = useTelemetry()
  const [scale, setScale] = useState(1)

  // ── Responsive scaling: observe container width ──
  useEffect(() => {
    const el = containerRef.current
    if (!el) return
    const observer = new ResizeObserver(([entry]) => {
      setScale(entry.contentRect.width / NATIVE_W)
    })
    observer.observe(el)
    return () => observer.disconnect()
  }, [])

  // ── Post telemetry data to iframe on every update ──
  useEffect(() => {
    const iframe = iframeRef.current
    if (!iframe?.contentWindow || !data) return
    iframe.contentWindow.postMessage(
      { type: 'k10-telemetry', snapshot: data },
      '*',
    )
  }, [data])

  return (
    <div className="flex flex-col gap-3">
      <span className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)]">
        Live Dashboard Demo
      </span>

      {/* Dashboard iframe — rendered at native size, scaled to fit container */}
      <div
        ref={containerRef}
        className="relative rounded-xl overflow-hidden border border-[var(--border-subtle)]"
        style={{ background: '#000', height: NATIVE_H * scale }}
      >
        {status !== 'live' && (
          <div className="absolute inset-0 flex items-center justify-center z-10" style={{ background: '#000' }}>
            <span className="text-sm text-[var(--text-dim)] animate-pulse">
              Connecting to telemetry...
            </span>
          </div>
        )}
        <iframe
          ref={iframeRef}
          src="/_demo/dashboard-embed.html"
          title="K10 Motorsports Dashboard Demo"
          className="border-0"
          sandbox="allow-scripts allow-same-origin"
          style={{
            background: '#000',
            opacity: status === 'live' ? 1 : 0,
            transition: 'opacity 0.5s ease',
            width: NATIVE_W,
            height: NATIVE_H,
            transform: `scale(${scale})`,
            transformOrigin: 'top left',
          }}
        />
      </div>
    </div>
  )
}
