import { db } from '@/db'
import { designTokens } from '@/db/schema'

interface DesignToken {
  path: string
  value: string
  kind: string
  cssProperty: string
  description?: string
  wcag?: string
  platforms: 'both' | 'overlay' | 'web'
  category: string
  sortOrder: number
}

const tokens: DesignToken[] = [
  // ── Background tokens (category: "background") ──
  {
    path: 'color.background.base',
    value: 'hsla(0, 0%, 8%, 0.90)',
    kind: 'color',
    cssProperty: '--bg',
    platforms: 'both',
    description: 'Main dashboard/page background',
    category: 'background',
    sortOrder: 0,
  },
  {
    path: 'color.background.surface',
    value: 'rgba(16, 16, 32, 0.90)',
    kind: 'color',
    cssProperty: '--bg-surface',
    platforms: 'web',
    description: 'Surface containers',
    category: 'background',
    sortOrder: 1,
  },
  {
    path: 'color.background.panel',
    value: 'hsla(0, 0%, 6%, 0.90)',
    kind: 'color',
    cssProperty: '--bg-panel',
    platforms: 'both',
    description: 'Panel interiors',
    category: 'background',
    sortOrder: 2,
  },
  {
    path: 'color.background.elevated',
    value: 'rgba(24, 24, 48, 0.85)',
    kind: 'color',
    cssProperty: '--bg-elevated',
    platforms: 'web',
    description: 'Elevated surfaces, popovers',
    category: 'background',
    sortOrder: 3,
  },
  {
    path: 'color.background.logo',
    value: 'hsla(0, 0%, 12%, 0.90)',
    kind: 'color',
    cssProperty: '--bg-logo',
    platforms: 'overlay',
    description: 'Logo square background',
    category: 'background',
    sortOrder: 4,
  },
  {
    path: 'color.background.overlay',
    value: 'hsla(220, 25%, 6%, 0.96)',
    kind: 'color',
    cssProperty: '--bg-overlay',
    platforms: 'overlay',
    description: 'Modal overlays (grid, settings)',
    category: 'background',
    sortOrder: 5,
  },

  // ── Text tokens (category: "text") ──
  {
    path: 'color.text.primary',
    value: 'hsla(0, 0%, 100%, 1.0)',
    kind: 'color',
    cssProperty: '--text-primary',
    platforms: 'both',
    description: 'Primary text, full white',
    wcag: '19.5:1 AAA',
    category: 'text',
    sortOrder: 10,
  },
  {
    path: 'color.text.secondary',
    value: 'rgba(255, 255, 255, 0.69)',
    kind: 'color',
    cssProperty: '--text-secondary',
    platforms: 'both',
    description: 'Labels, secondary content',
    wcag: '9.3:1 AAA',
    category: 'text',
    sortOrder: 11,
  },
  {
    path: 'color.text.dim',
    value: 'rgba(255, 255, 255, 0.55)',
    kind: 'color',
    cssProperty: '--text-dim',
    platforms: 'both',
    description: 'Tertiary text, units',
    wcag: '5.9:1 AA',
    category: 'text',
    sortOrder: 12,
  },
  {
    path: 'color.text.muted',
    value: 'rgba(255, 255, 255, 0.45)',
    kind: 'color',
    cssProperty: '--text-muted',
    platforms: 'web',
    description: 'Muted text, placeholders',
    wcag: '4.0:1 AA-large',
    category: 'text',
    sortOrder: 13,
  },
  {
    path: 'color.text.web-primary',
    value: '#e8e8f0',
    kind: 'color',
    cssProperty: '--text',
    platforms: 'web',
    description: 'Web primary text alias',
    wcag: '16.2:1 AAA',
    category: 'text',
    sortOrder: 14,
  },

  // ── Border tokens (category: "border") ──
  {
    path: 'color.border.default',
    value: 'rgba(255, 255, 255, 0.14)',
    kind: 'color',
    cssProperty: '--border',
    platforms: 'both',
    description: 'Standard panel borders',
    category: 'border',
    sortOrder: 20,
  },
  {
    path: 'color.border.subtle',
    value: 'rgba(255, 255, 255, 0.06)',
    kind: 'color',
    cssProperty: '--border-subtle',
    platforms: 'web',
    description: 'Subtle dividers',
    category: 'border',
    sortOrder: 21,
  },
  {
    path: 'color.border.accent',
    value: 'rgba(229, 57, 53, 0.35)',
    kind: 'color',
    cssProperty: '--border-accent',
    platforms: 'web',
    description: 'Red accent borders',
    category: 'border',
    sortOrder: 22,
  },
  {
    path: 'color.border.track-stroke',
    value: 'rgba(255, 255, 255, 0.18)',
    kind: 'color',
    cssProperty: '--track-stroke',
    platforms: 'web',
    description: 'Track map SVG stroke color. Neutral in K10 default; overridden to brand color per team set.',
    category: 'border',
    sortOrder: 23,
  },
  {
    path: 'color.border.active',
    value: 'hsla(0, 0%, 100%, 0.25)',
    kind: 'color',
    cssProperty: '--border-active',
    platforms: 'overlay',
    description: 'Highlighted active borders',
    category: 'border',
    sortOrder: 23,
  },

  // ── Brand tokens (category: "brand") ──
  {
    path: 'color.brand.red',
    value: '#e53935',
    kind: 'color',
    cssProperty: '--red',
    platforms: 'both',
    description: 'Primary brand red, danger, brake',
    wcag: '4.7:1 AA',
    category: 'brand',
    sortOrder: 30,
  },
  {
    path: 'color.brand.red-mid',
    value: '#b02020',
    kind: 'color',
    cssProperty: '--k10-red-mid',
    platforms: 'web',
    description: 'Mid-tone brand red',
    wcag: '3.3:1 AA-large',
    category: 'brand',
    sortOrder: 31,
  },
  {
    path: 'color.brand.red-dark',
    value: '#700010',
    kind: 'color',
    cssProperty: '--k10-red-dark',
    platforms: 'web',
    description: 'Dark brand red, backgrounds only',
    wcag: '2.0:1 FAIL',
    category: 'brand',
    sortOrder: 32,
  },

  // ── Semantic color tokens (category: "semantic") ──
  {
    path: 'color.semantic.green',
    value: '#43a047',
    kind: 'color',
    cssProperty: '--green',
    platforms: 'both',
    description: 'Optimal, throttle, ahead, clear',
    category: 'semantic',
    sortOrder: 40,
  },
  {
    path: 'color.semantic.blue',
    value: '#1e88e5',
    kind: 'color',
    cssProperty: '--blue',
    platforms: 'both',
    description: 'Clutch, info, neutral state',
    category: 'semantic',
    sortOrder: 41,
  },
  {
    path: 'color.semantic.amber',
    value: '#ffb300',
    kind: 'color',
    cssProperty: '--amber',
    platforms: 'both',
    description: 'Caution, warning, yellow flag',
    category: 'semantic',
    sortOrder: 42,
  },
  {
    path: 'color.semantic.orange',
    value: '#fb8c00',
    kind: 'color',
    cssProperty: '--orange',
    platforms: 'both',
    description: 'Close proximity, alert',
    category: 'semantic',
    sortOrder: 43,
  },
  {
    path: 'color.semantic.cyan',
    value: '#00acc1',
    kind: 'color',
    cssProperty: '--cyan',
    platforms: 'both',
    description: 'Player highlight, primary action',
    category: 'semantic',
    sortOrder: 44,
  },
  {
    path: 'color.semantic.purple',
    value: 'hsl(280, 80%, 70%)',
    kind: 'color',
    cssProperty: '--purple',
    platforms: 'both',
    description: 'Session best lap time',
    category: 'semantic',
    sortOrder: 45,
  },

  // ── Flag tokens (category: "flag") ──
  {
    path: 'color.flag.yellow',
    value: 'hsl(48, 95%, 55%)',
    kind: 'color',
    cssProperty: '--flag-yellow',
    platforms: 'overlay',
    description: 'Yellow flag',
    category: 'flag',
    sortOrder: 50,
  },
  {
    path: 'color.flag.red',
    value: 'hsl(0, 85%, 55%)',
    kind: 'color',
    cssProperty: '--flag-red',
    platforms: 'overlay',
    description: 'Red flag',
    category: 'flag',
    sortOrder: 51,
  },
  {
    path: 'color.flag.blue',
    value: 'hsl(220, 80%, 60%)',
    kind: 'color',
    cssProperty: '--flag-blue',
    platforms: 'overlay',
    description: 'Blue flag',
    category: 'flag',
    sortOrder: 52,
  },
  {
    path: 'color.flag.green',
    value: 'hsl(130, 75%, 58%)',
    kind: 'color',
    cssProperty: '--flag-green',
    platforms: 'overlay',
    description: 'Green flag',
    category: 'flag',
    sortOrder: 53,
  },
  {
    path: 'color.flag.white',
    value: 'hsl(0, 0%, 92%)',
    kind: 'color',
    cssProperty: '--flag-white',
    platforms: 'overlay',
    description: 'White flag',
    category: 'flag',
    sortOrder: 54,
  },
  {
    path: 'color.flag.debris',
    value: 'hsl(45, 90%, 65%)',
    kind: 'color',
    cssProperty: '--flag-debris',
    platforms: 'overlay',
    description: 'Debris flag',
    category: 'flag',
    sortOrder: 55,
  },

  // ── Typography tokens (category: "typography") ──
  {
    path: 'typography.fontFamily.base',
    value: "'Barlow Condensed', 'Corbel', 'Segoe UI', system-ui, sans-serif",
    kind: 'font',
    cssProperty: '--ff',
    platforms: 'both',
    description: 'Primary UI font',
    category: 'typography',
    sortOrder: 60,
  },
  {
    path: 'typography.fontFamily.display',
    value: "'Cinzel Decorative', 'Georgia', serif",
    kind: 'font',
    cssProperty: '--ff-display',
    platforms: 'both',
    description: 'Display/decorative font',
    category: 'typography',
    sortOrder: 61,
  },
  {
    path: 'typography.fontFamily.mono',
    value: "'JetBrains Mono', 'Consolas', 'SF Mono', monospace",
    kind: 'font',
    cssProperty: '--ff-mono',
    platforms: 'both',
    description: 'Monospace font for timing data',
    category: 'typography',
    sortOrder: 62,
  },
  {
    path: 'typography.fontSize.xl',
    value: '20px',
    kind: 'size',
    cssProperty: '--fs-xl',
    platforms: 'both',
    category: 'typography',
    sortOrder: 63,
  },
  {
    path: 'typography.fontSize.lg',
    value: '13px',
    kind: 'size',
    cssProperty: '--fs-lg',
    platforms: 'both',
    category: 'typography',
    sortOrder: 64,
  },
  {
    path: 'typography.fontSize.md',
    value: '11px',
    kind: 'size',
    cssProperty: '--fs-md',
    platforms: 'both',
    category: 'typography',
    sortOrder: 65,
  },
  {
    path: 'typography.fontSize.sm',
    value: '11px',
    kind: 'size',
    cssProperty: '--fs-sm',
    platforms: 'both',
    category: 'typography',
    sortOrder: 66,
  },
  {
    path: 'typography.fontSize.xs',
    value: '10px',
    kind: 'size',
    cssProperty: '--fs-xs',
    platforms: 'both',
    category: 'typography',
    sortOrder: 67,
  },
  {
    path: 'typography.fontWeight.black',
    value: '800',
    kind: 'weight',
    cssProperty: '--fw-black',
    platforms: 'both',
    description: 'Maximum prominence',
    category: 'typography',
    sortOrder: 68,
  },
  {
    path: 'typography.fontWeight.bold',
    value: '700',
    kind: 'weight',
    cssProperty: '--fw-bold',
    platforms: 'both',
    description: 'Strong emphasis',
    category: 'typography',
    sortOrder: 69,
  },
  {
    path: 'typography.fontWeight.semi',
    value: '600',
    kind: 'weight',
    cssProperty: '--fw-semi',
    platforms: 'both',
    description: 'Labels, secondary emphasis',
    category: 'typography',
    sortOrder: 70,
  },
  {
    path: 'typography.fontWeight.medium',
    value: '500',
    kind: 'weight',
    cssProperty: '--fw-medium',
    platforms: 'both',
    description: 'Body text',
    category: 'typography',
    sortOrder: 71,
  },
  {
    path: 'typography.fontWeight.regular',
    value: '400',
    kind: 'weight',
    cssProperty: '--fw-regular',
    platforms: 'both',
    description: 'Baseline weight',
    category: 'typography',
    sortOrder: 72,
  },

  // ── Spacing tokens (category: "spacing") ──
  {
    path: 'spacing.gap',
    value: '4px',
    kind: 'size',
    cssProperty: '--gap',
    platforms: 'overlay',
    description: 'Inter-panel gap',
    category: 'spacing',
    sortOrder: 80,
  },
  {
    path: 'spacing.panelGap',
    value: '6px',
    kind: 'size',
    cssProperty: '--panel-gap',
    platforms: 'overlay',
    description: 'Gap between secondary panels',
    category: 'spacing',
    sortOrder: 81,
  },
  {
    path: 'spacing.edge',
    value: '10px',
    kind: 'size',
    cssProperty: '--edge',
    platforms: 'overlay',
    description: 'Screen edge offset',
    category: 'spacing',
    sortOrder: 82,
  },
  {
    path: 'spacing.pad',
    value: '6px',
    kind: 'size',
    cssProperty: '--pad',
    platforms: 'overlay',
    description: 'Standard internal padding',
    category: 'spacing',
    sortOrder: 83,
  },

  // ── Radius tokens (category: "spacing") ──
  {
    path: 'radius.default',
    value: '8px',
    kind: 'radius',
    cssProperty: '--corner-r',
    platforms: 'both',
    description: 'Main panel corners',
    category: 'spacing',
    sortOrder: 84,
  },
  {
    path: 'radius.small',
    value: '5px',
    kind: 'radius',
    cssProperty: '--corner-r-sm',
    platforms: 'both',
    description: 'Internal element corners',
    category: 'spacing',
    sortOrder: 85,
  },

  // ── Timing/animation tokens (category: "timing") ──
  {
    path: 'animation.fast',
    value: '180ms ease',
    kind: 'timing',
    cssProperty: '--t-fast',
    platforms: 'both',
    description: 'Quick state changes',
    category: 'timing',
    sortOrder: 90,
  },
  {
    path: 'animation.medium',
    value: '350ms ease',
    kind: 'timing',
    cssProperty: '--t-med',
    platforms: 'both',
    description: 'Standard transitions',
    category: 'timing',
    sortOrder: 91,
  },
  {
    path: 'animation.slow',
    value: '600ms ease-out',
    kind: 'timing',
    cssProperty: '--t-slow',
    platforms: 'both',
    description: 'Major layout changes',
    category: 'timing',
    sortOrder: 92,
  },

  // ── Layout tokens (category: "layout") ──
  {
    path: 'layout.dashHeight',
    value: '200px',
    kind: 'size',
    cssProperty: '--dash-h',
    platforms: 'overlay',
    description: 'Dashboard total height',
    category: 'layout',
    sortOrder: 100,
  },
  {
    path: 'layout.rowHeight',
    value: 'calc((var(--dash-h) - var(--gap)) / 2)',
    kind: 'size',
    cssProperty: '--row-h',
    platforms: 'overlay',
    description: 'Per-row height',
    category: 'layout',
    sortOrder: 101,
  },

  // ── Sentiment tokens (category: "opacity", overlay-only runtime vars) ──
  {
    path: 'color.sentiment.hue',
    value: '0',
    kind: 'color',
    cssProperty: '--sentiment-h',
    platforms: 'overlay',
    description: 'Sentiment hue (runtime)',
    category: 'opacity',
    sortOrder: 110,
  },
  {
    path: 'color.sentiment.saturation',
    value: '0%',
    kind: 'color',
    cssProperty: '--sentiment-s',
    platforms: 'overlay',
    description: 'Sentiment saturation (runtime)',
    category: 'opacity',
    sortOrder: 111,
  },
  {
    path: 'color.sentiment.lightness',
    value: '0%',
    kind: 'color',
    cssProperty: '--sentiment-l',
    platforms: 'overlay',
    description: 'Sentiment lightness (runtime)',
    category: 'opacity',
    sortOrder: 112,
  },
  {
    path: 'color.sentiment.alpha',
    value: '0',
    kind: 'opacity',
    cssProperty: '--sentiment-alpha',
    platforms: 'overlay',
    description: 'Sentiment alpha (runtime)',
    category: 'opacity',
    sortOrder: 113,
  },
]

export async function seedDesignTokens() {
  console.log(`Seeding ${tokens.length} design tokens...`)

  for (const token of tokens) {
    await db
      .insert(designTokens)
      .values(token)
      .onConflictDoUpdate({
        target: designTokens.path,
        set: {
          value: token.value,
          kind: token.kind,
          cssProperty: token.cssProperty,
          description: token.description ?? null,
          wcag: token.wcag ?? null,
          platforms: token.platforms,
          category: token.category,
          sortOrder: token.sortOrder,
          updatedAt: new Date(),
        },
      })
  }

  console.log('Done seeding design tokens.')
}

// Allow running directly: npx tsx web/src/lib/tokens/seed.ts
if (require.main === module) {
  seedDesignTokens()
    .then(() => process.exit(0))
    .catch((e) => {
      console.error(e)
      process.exit(1)
    })
}
